version: "3"

services:
  db:
    environment:
      POSTGRES_DB: db_app
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    restart: on-failure
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: docker/local/Dockerfile.web
    command: /start.sh
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      MAILJET_API_KEY: 9298092812312312312
      MAILJET_SECRET_KEY: 987654321
      REG_START_DATE: "2023-08-30"
      REG_END_DATE: "2023-09-30"
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
