# Generated by Django 4.2.3 on 2023-07-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='Vorname')),
                ('lastname', models.CharField(max_length=200, verbose_name='Nachname')),
                ('administrative_appl', models.BooleanField(blank=True, null=True, verbose_name='Verwaltungsfachangestellte*r')),
                ('media_appl', models.BooleanField(blank=True, null=True, verbose_name='Fachangestellte*r für Medien- und Informationsdienste')),
                ('soldier', models.BooleanField(blank=True, null=True, verbose_name='Soldat*in')),
                ('disability', models.BooleanField(blank=True, null=True, verbose_name='Einschränkungen')),
            ],
            options={
                'verbose_name': 'Bewerber*in',
                'verbose_name_plural': 'Bewerber*innen',
            },
        ),
    ]
