# Generated by Django 4.2.3 on 2023-07-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_mask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(default='', max_length=300, verbose_name='Email'),
        ),
    ]
