# Generated by Django 4.2.3 on 2023-07-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_mask', '0002_applicant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='inspector_appl',
            field=models.BooleanField(blank=True, null=True, verbose_name='Inspektoranwärter*in'),
        ),
    ]
