# Generated by Django 4.2.3 on 2025-08-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_mask', '0003_applicant_inspector_appl'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('m', 'männlich'), ('w', 'weiblich'), ('d', 'divers')], default='d', max_length=1, verbose_name='Geschlecht'),
        ),
    ]
